version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: controle-estoque-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: controle_estoque
      MYSQL_DATABASE_DEV: controle_estoque_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: controle-estoque-app
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_USERNAME: root
      DB_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/controle_estoque
    ports:
      - "8080:8080"
    networks:
      - estoque-network

networks:
  estoque-network:
    driver: bridge

volumes:
  mysql_data:
